platform :ios, '12.0'

target 'AudioburstPlayerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for AudioburstPlayerDemo
  pod 'AudioburstPlayer'
  pod 'Tabman', '~> 2.9'
end
